---

- hosts: localhost

  vars:
    ssh_users:
      - name: alice
        sshkey:
          - 'ssh-rsa key-1'
          - 'ssh-rsa key-2'

  tasks:
  - name: Deploy SSH-Keys to remote host
    authorized_key:
      user: levi
      key: "{{ '\n'.join(ssh_users|map(attribute='sshkey')|flatten) }}"
      state: present
      exclusive: true